// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aadvtfotgmxbhofiebwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhZHZ0Zm90Z214YmhvZmllYndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3Njc0MzcsImV4cCI6MjA2MTM0MzQzN30.Q1jqZHtz3c8PhG2_6l0G2KTzZVIy9LTIb-icNzxvjxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);